# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service  # This should match the matrix service name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service  # This should also match the matrix service name
          image: ghcr.io/yourusername/your-repo-service1:latest  # This will be updated by kubectl set image
          ports:
            - containerPort: 8081
          env:
            - name: JWT_TOKEN
              value: ${{ secrets.JWT_TOKEN }}
            - name: JWT_EXPIRATION
              value: ${{ secrets.JWT_EXPIRATION }}
      imagePullSecrets:
        - name: github-registry