server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quantumcashdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/quantumcashdb
    user: postgres
    password: postgres
    schemas: account_service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

  redis:
    host: localhost
    port: 6379

auth:
  service:
    url: http://localhost:8081

notification:
  service:
    url: http://localhost:8086